name: Flutter Tests

on:
  push:
    branches: [ main, 'claude/**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.8.1'
        channel: 'stable'
        cache: true
    
    - name: Get Flutter dependencies
      run: |
        cd free_flight_log_app
        flutter pub get
    
    - name: Analyze code
      run: |
        cd free_flight_log_app
        flutter analyze
    
    - name: Run DatabaseService tests
      run: |
        cd free_flight_log_app
        flutter test test/database_service_test.dart --coverage --reporter=expanded
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./free_flight_log_app/coverage/lcov.info
        fail_ci_if_error: false
        verbose: true